name: Test PR
on:
  push:
    branches: 
      - scala3
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.12.1
                  cache: npm
            - run: npm ci

    test:
        needs: [build]
        runs-on: ${{ matrix.runs-on }}

        strategy:
            fail-fast: true

            matrix:
                fixture:
                    - typescript
                    # - javascript,schema-javascript
                    # - golang,schema-golang
                    # - cplusplus,schema-cplusplus
                    # - flow,schema-flow
                    # - java,schema-java
                    # - python,schema-python
                    # - haskell,schema-haskell
                    # - csharp,schema-csharp,schema-json-csharp,graphql-csharp,csharp-SystemTextJson
                    # - json-ts-csharp
                    # - dart,schema-dart
                    # - swift,schema-swift
                    # - javascript-prop-types
                    # - ruby
                    - scala3

                    # Partially working
                    # - schema-typescript # TODO Unify with typescript once fixed

                    # Implementation is too outdated to test in GitHub Actions
                    # - elm,schema-elm

                    # Language is too niche / obscure to test easily on ubuntu-latest
                    # - pike,schema-pike

                    # Not yet started
                    # @schani can you help me understand this fixture?
                    # It looks like it tests 13+ languages?
                    # - graphql

                    # Never tested?
                    # - crystal

                runs-on: [ubuntu-latest]

                #include:
                  # Rust is very slow, so we use a larger runner
                  #- fixture: rust,schema-rust
                    #runs-on: ubuntu-latest-8-cores
                  # Kotlin is also slow
                  #- fixture: kotlin,schema-kotlin,kotlin-jackson,schema-kotlin-jackson
                  #  runs-on: ubuntu-latest-8-cores

                  #- fixture: objective-c
                  #  runs-on: macos-11

        name: ${{ matrix.fixture }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.12.1
                  cache: npm

            - run: npm ci
            
            - name: Install scala
              if: ${{ contains(matrix.fixture, 'scala3') }}
              uses: VirtusLab/scala-cli-setup@main
            - run: echo '@main def hello() = println("Hello")' | scala-cli _
              if: ${{ contains(matrix.fixture, 'scala3') }}
            - run: QUICKTEST=true FIXTURE=${{ matrix.fixture }} npm test
